### ISSUE TITLE
Game Crash on 1.21

### ISSUE THREAD

**Issue by MeltedButter77** [Steaf23/BingoReloaded#43]
After some time playing (~15 minutes) i received this error.
[05:38:17 WARN]: [io.github.steaf23.bingoreloaded.easymenulib.packetevents.PacketEventsAPI] No data was sent for dimension Compound{{name=String(minecraft:overworld), id=Int(0)}} to Kheph

This causes the server to crash and the game starts over erasing current progress

**Comment by Steaf23** [comment]
Hey, could you give me the entire error or log file? it would help me trace down where the issue came from

**Comment by MeltedButter77** [comment]
Sure, here is the log file
https://mclo.gs/bPleSu4
it could be another plugin messing with it. but it was this plugin's error that seems to have caused the crash.

**Comment by Steaf23** [comment]
Hmm very odd that is abruptly ends after the warning. I did notice it also appeared near the start of the log file, maybe there is more going on. I wanted to make a small update to the plugin earlier adressing some issues so maybe that will fix this issue too. I plan to release it in the next few days. Before that you can try disabling other plugins to see if the crash was caused by something else for some reason.
Thanks for reporting

**Comment by MeltedButter77** [comment]
Sure will do, it does seem to happen randomly. So it does seem likely to be a different plugin. Ill let you know if it happens again :)

**Comment by MeltedButter77** [comment]
Its crashed a couple times now. ranging from 3 minutes in to 25.
This was a pretty long one https://mclo.gs/UEbB9Y1
Logs just abruptly end. idk how to get more info. The ONLY other plugin i have is essentialsX and essentialsX-discord. Also when a player used a bed and then broke it and died, they re-spawned at 0, 0.

lmk if there is a way to get more info about the crash

Paper 1.21-46

**Comment by Steaf23** [comment]
I see. I am planning to release that update I talked about today or tomorrow which might fix the issue as it probably has to do with external dependencies (packetevents), that's the only warning that's consistently being shown. The thing with the bed is just a plugin bug but I can probably fix that in the same update. Thanks for your patience :D

**Comment by MeltedButter77** [comment]
Alright, ill keep my eyes peeled!

**Comment by MeltedButter77** [comment]
fyi, just had another crash. Same packet error was present
https://mclo.gs/WhBQWJb

**Comment by Steaf23** [comment]
I released the update, please try it out and see of the crashes are gone. You will need to install packet events separately, as described in the notes https://github.com/Steaf23/BingoReloaded/releases/tag/v2.1.2

If this still doesn't solve the issue, I think you will have to send some timings or spark report and maybe we can work it out that way.

**Comment by MeltedButter77** [comment]
Ill use the new version with spark. How should i set spark so it can record the crash? Do i use a profiler or does it just do it on its own?

**Comment by Steaf23** [comment]
Thats actually something I didn't really think about. Crashes like these are very nasty because there is no information whatsoever. Furthermore I dont know if spark is able to help out since crashes are really hard to track, since the server just stops. You cab try /spark profiler when the server is started and then /spark --stop to get a link to the made profile, about 10 minutes in. If the crash is consistently at 15 minutes it could be a memory leak in which case spark would detect this pretty fast. Otherwise I dont know your setup, it could also depend on your host or container is you have any. Lastly stuff like closing the console will obviously also shut down the server.. I don't know if you have tried before but maybe disable or remove the plugin and see if it still crashes with everything else being the same

**Comment by MeltedButter77** [comment]
Im getting this error, and the it quickly crashes like before
[11:40:20 ERROR]: [BingoReloaded]: Cannot find any teams to join! Wait for the game to re-open (if it still happens after the game is re-opened, Please report!)

**Comment by Steaf23** [comment]
Can you send your config.yml file? and also inside the plugin folder there should be a folder called data, inside is a file called teams.yml, make sure that is not empty.. Can you tell me when this error appears? You cannot join a team when a game is running so then you might receive this error too. All it should be doing is preventing you from joining the game, not crashing the server haha

**Comment by Steaf23** [comment]
and you are playing the latest paper experimental correct?

**Comment by MeltedButter77** [comment]
Sorry for wasting your time, this turned out to be a problem on my end :/
Took me tens of hours to work it out.
